// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdxglfncaulbjvbbirrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkeGdsZm5jYXVsYmp2YmJpcnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NzkwMzEsImV4cCI6MjA4NTI1NTAzMX0.4o3v-dVjVRY2mRmEITuePzILzYYZN-StzdB8cnc1maM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Next.js build/prerender runs on the server where localStorage doesn't exist.
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  },
});